name: Unit Tests

on:
  workflow_call:
    # secrets:
    #   GH_TOKEN:
    #     description: 'GitHub Token'
    #     required: true
  push:
    branches:
      - '*'
      - '!deploy'
      - '!gh-pages'

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose version || sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o ./docker-compose.yml
          sudo chmod +x ./docker-compose.yml

      - name: Load .env variables
        run: |
          DB_HOST=localhost
          DB_PORT=5432
          DB_USER=postgres
          DB_PASS=postgres
          DB_NAME=test

      - name: Start database service
        run: docker compose up -d

      - name: Wait for database
        run: |
          until docker exec $(docker ps -q -f name=db) pg_isready -U $DB_USER; do
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run Vitest tests
        run: npm run test:unit

      - name: Stop database service
        if: always()
        run: docker compose down